[package]
name = "grideye_tui"
version = "0.1.0"
edition = "2021"
authors = ["prace@srbpavel.cz <prace@srbpavel.cz>"]

[dependencies]
log = "0.4"
env_logger = "0.10.0"

termion = "2.0.1"
#crossterm = "0.26.0"

tui = { version = "0.19", default-features = false, features = ['termion'] }

rumqttc = "0.10.0"
chrono = "0.4.23"

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",                # Lets you generate random UUIDs                  
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
